"""changes in post tables after creating routers 9

Revision ID: 0343d875ba98
Revises: 4a477ae4d751
Create Date: 2024-01-04 03:37:23.116142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0343d875ba98'
down_revision: Union[str, None] = '4a477ae4d751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
