"""changes in post tables after creating routers 2

Revision ID: 0a22479b1a55
Revises: e44308d455a4
Create Date: 2024-01-04 02:20:36.566256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a22479b1a55'
down_revision: Union[str, None] = 'e44308d455a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
