"""deleted at course

Revision ID: 1c600040968d
Revises: 401d3453aa61
Create Date: 2024-01-17 22:10:19.371047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c600040968d'
down_revision: Union[str, None] = '401d3453aa61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SPSCourse', 'Name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('SPSCourse', 'IsValidPUPQCCourses',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('SPSCourse', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('SPSCourse', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('SPSCourseEnrolled', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('SPSCourseEnrolled', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SPSCourseEnrolled', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('SPSCourseEnrolled', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('SPSCourse', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('SPSCourse', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('SPSCourse', 'IsValidPUPQCCourses',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('SPSCourse', 'Name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
