"""changes in post tables after creating routers 8

Revision ID: 4a477ae4d751
Revises: 992aeb99adaf
Create Date: 2024-01-04 03:32:02.037640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a477ae4d751'
down_revision: Union[str, None] = '992aeb99adaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
