"""changes in post tables after creating routers 3

Revision ID: 4f13d1b10dc2
Revises: 0a22479b1a55
Create Date: 2024-01-04 02:34:28.411339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f13d1b10dc2'
down_revision: Union[str, None] = '0a22479b1a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('approver_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('donation_approved_by_user_id_fkey', 'donation', type_='foreignkey')
    op.create_foreign_key(None, 'donation', 'user', ['approver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('donation', 'approved_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('approved_by_user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'donation', type_='foreignkey')
    op.create_foreign_key('donation_approved_by_user_id_fkey', 'donation', 'user', ['approved_by_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('donation', 'approver_id')
    # ### end Alembic commands ###
