"""aded user column: is_compelted

Revision ID: 4fc446324878
Revises: f03e7db4de3e
Create Date: 2023-12-18 03:26:16.520978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc446324878'
down_revision: Union[str, None] = 'f03e7db4de3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_completed', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_completed')
    # ### end Alembic commands ###
