"""removed code and certified at job

Revision ID: 72853b6cb381
Revises: ec75c7226950
Create Date: 2023-12-23 06:43:43.436929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72853b6cb381'
down_revision: Union[str, None] = 'ec75c7226950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_code', table_name='job')
    op.drop_column('job', 'code')
    op.drop_column('job', 'certified_job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('certified_job', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('job', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_job_code', 'job', ['code'], unique=False)
    # ### end Alembic commands ###
