"""added columns for setting up the analytics

Revision ID: 848217e01385
Revises: 4fc446324878
Create Date: 2023-12-21 01:34:58.945459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848217e01385'
down_revision: Union[str, None] = '4fc446324878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_course_code'), 'course', ['code'], unique=False)
    op.add_column('employment', sa.Column('alligned_with_course', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('job', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_job_code'), 'job', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_code'), table_name='job')
    op.drop_column('job', 'code')
    op.drop_column('employment', 'alligned_with_course')
    op.drop_index(op.f('ix_course_code'), table_name='course')
    op.drop_column('course', 'code')
    # ### end Alembic commands ###
