"""added batch year

Revision ID: 8c85767ac080
Revises: c83f8f12fe9c
Create Date: 2023-12-22 02:22:08.327043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c85767ac080'
down_revision: Union[str, None] = 'c83f8f12fe9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('batch_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'batch_year')
    # ### end Alembic commands ###
