"""changes in post tables after creating routers 7

Revision ID: 992aeb99adaf
Revises: 8516788af9b4
Create Date: 2024-01-04 03:19:35.691056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992aeb99adaf'
down_revision: Union[str, None] = '8516788af9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
