"""cleared out the video link and content date

Revision ID: 9ff5be5e5da1
Revises: 059f0c711d44
Create Date: 2024-01-12 13:29:53.262569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff5be5e5da1'
down_revision: Union[str, None] = '059f0c711d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('content_date', sa.Date(), nullable=True))
    op.drop_column('event', 'event_date')
    op.drop_column('post', 'content_date')
    op.drop_column('post', 'video_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('video_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('content_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('event', 'content_date')
    # ### end Alembic commands ###
