"""added certified_job

Revision ID: b11d405f5ac0
Revises: 848217e01385
Create Date: 2023-12-21 01:59:13.262006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11d405f5ac0'
down_revision: Union[str, None] = '848217e01385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('job', sa.Column('certified_job', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('job', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('job', 'certified_job')
    op.alter_column('course', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
