"""removed supporting links

Revision ID: b98b0cbca3dd
Revises: 0343d875ba98
Create Date: 2024-01-04 09:44:58.817653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98b0cbca3dd'
down_revision: Union[str, None] = '0343d875ba98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'supporting_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('supporting_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
