"""changes in post tables after creating routers 4

Revision ID: c764a538a3ed
Revises: 4f13d1b10dc2
Create Date: 2024-01-04 02:39:12.125135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c764a538a3ed'
down_revision: Union[str, None] = '4f13d1b10dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
