"""renamed to aligned_with_academic_program

Revision ID: c83f8f12fe9c
Revises: b11d405f5ac0
Create Date: 2023-12-21 02:04:36.473863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83f8f12fe9c'
down_revision: Union[str, None] = 'b11d405f5ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment', sa.Column('aligned_with_academic_program', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('employment', 'alligned_with_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment', sa.Column('alligned_with_course', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('employment', 'aligned_with_academic_program')
    # ### end Alembic commands ###
