"""interestevent

Revision ID: cd3d15407db6
Revises: a42403b610bc
Create Date: 2024-02-21 10:37:33.685097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3d15407db6'
down_revision: Union[str, None] = 'a42403b610bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('APMSUserInterestEvent', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('APMSUserInterestEvent', sa.Column('UserID', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('APMSUserInterestEvent', sa.Column('EventID', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('APMSUserInterestEvent', sa.Column('AnnouncementID', type_=sa.Integer(), nullable=True))
    op.drop_constraint('APMSUserInterestEvent_UserId_fkey', 'APMSUserInterestEvent', type_='foreignkey')
    op.drop_constraint('APMSUserInterestEvent_EventId_fkey', 'APMSUserInterestEvent', type_='foreignkey')
    op.create_foreign_key(None, 'APMSUserInterestEvent', 'APMSPost', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(
        None,
        'APMSUserInterestEvent',
        'ESISAnnouncement',
        ['AnnouncementID'],
        ['AnnouncementId'],
        ondelete='CASCADE',
        source_column_type=postgresql.UUID(as_uuid=True),
        referent_column_type=postgresql.UUID(as_uuid=True)
    )
    op.create_foreign_key(None, 'APMSUserInterestEvent', 'APMSEvent', ['EventID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'APMSUserInterestEvent', 'APMSUser', ['UserID'], ['id'], ondelete='CASCADE')
    op.drop_column('APMSUserInterestEvent', 'UserId')
    op.drop_column('APMSUserInterestEvent', 'EventId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('APMSUserInterestEvent', sa.Column('EventId', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('APMSUserInterestEvent', sa.Column('UserId', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'APMSUserInterestEvent', type_='foreignkey')
    op.drop_constraint(None, 'APMSUserInterestEvent', type_='foreignkey')
    op.drop_constraint(None, 'APMSUserInterestEvent', type_='foreignkey')
    op.drop_constraint(None, 'APMSUserInterestEvent', type_='foreignkey')
    op.create_foreign_key('APMSUserInterestEvent_EventId_fkey', 'APMSUserInterestEvent', 'APMSEvent', ['EventId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('APMSUserInterestEvent_UserId_fkey', 'APMSUserInterestEvent', 'APMSUser', ['UserId'], ['id'], ondelete='CASCADE')
    op.drop_column('APMSUserInterestEvent', 'AnnouncementID')
    op.drop_column('APMSUserInterestEvent', 'EventID')
    op.drop_column('APMSUserInterestEvent', 'UserID')
    op.drop_column('APMSUserInterestEvent', 'id')
    # ### end Alembic commands ###
