"""changes in post tables after creating routers

Revision ID: e44308d455a4
Revises: ed87a08b3f2c
Create Date: 2024-01-04 02:13:15.151406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e44308d455a4'
down_revision: Union[str, None] = 'ed87a08b3f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_date', sa.Date(), nullable=True))
    op.drop_column('event', 'start_date')
    op.add_column('post', sa.Column('video_link', sa.String(), nullable=True))
    op.add_column('post', sa.Column('uploader_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['uploader_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'uploader_id')
    op.drop_column('post', 'video_link')
    op.add_column('event', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('event', 'event_date')
    # ### end Alembic commands ###
