"""removed date start in pup selected course

Revision ID: f03e7db4de3e
Revises: f7f9a7f74886
Create Date: 2023-12-18 01:55:35.857986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03e7db4de3e'
down_revision: Union[str, None] = 'f7f9a7f74886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
