"""added finding job means column

Revision ID: f7f9a7f74886
Revises: 9410935f2ff4
Create Date: 2023-12-14 04:01:10.262477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f9a7f74886'
down_revision: Union[str, None] = '9410935f2ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment', sa.Column('finding_job_means', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employment', 'finding_job_means')
    # ### end Alembic commands ###
